import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { AuthProvider } from '@/context/AuthContext';
import { DataProvider } from '@/context/DataContext';
import { DialogProvider } from '@/context/DialogContext';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased font-sans`}
      >
        <AuthProvider>
          <DialogProvider>
            <DataProvider>
              {children}
            </DataProvider>
          </DialogProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
